### ISSUE TITLE
parse error with command

### ISSUE THREAD

**Issue by Karstedt-019** [justbetter/magento2-akeneo-bundle#11]
Just tried updating from 1.2 to 1.3.2 and the new one throws a parse error when trying to do anything from the cli

Parse error: syntax error, unexpected 'ImportMetricUnitsJob' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in .../vendor/justbetter/magento2-akeneo-bundle/Console/Command/ImportMetricUnits.php on line 12

**Comment by VincentBean** [comment]
What PHP version are you using?

**Comment by VincentBean** [comment]
PHP 7.4 is required from version 1.3.
