### ISSUE TITLE
How to make it works?

### ISSUE THREAD

**Issue by Chrislimbic** [justbetter/magento2-akeneo-bundle#2]
Hello,

We are using your Magento2 Akeneo Bundle module in order to import per product tax classes and we cannot make it works. We have an Akeneo select attribute called "vat_type" with 4 options: standard, reduced, superreduced and no_vat. We configured your Tax Id Mapping assigning every option to one Magento's VAT option but it does not work. Also, we tried to map Akeneo's "vat_type" to Magento's "tax_class_id" without success. There is no documentation about how to use your module. Could you please tell us how to make it works? Thank you in advance.

Best regards,
Chris

**Comment by pimruiter** [comment]
Hi Chris,

Thanks for your question! Please try to configure the tax type to the attribute within the Akeneo connector Attributes configuration:

![image](https://user-images.githubusercontent.com/16269189/120282794-cd5c0e80-c2ba-11eb-912e-9611bed71e09.png)

Let me know if it works, so I can update the documentation.

Kind Regards,
Pim

**Comment by Chrislimbic** [comment]
> Hi Chris,
> 
> Thanks for your question! Please try to configure the tax type to the attribute within the Akeneo connector Attributes configuration:
> 
> ![image](https://user-images.githubusercontent.com/16269189/120282794-cd5c0e80-c2ba-11eb-912e-9611bed71e09.png)
> 
> Let me know if it works, so I can update the documentation.
> 
> Kind Regards,
> Pim

It works. Thank you so much.
