### ISSUE TITLE
How the tier pricing working

### ISSUE THREAD

**Issue by JoostWan** [justbetter/magento2-akeneo-bundle#27]
I will that the module also has support for tier pricing. On the Akeneo side, how does it work with tiers? Do attributes need to be created for this? I had a quick look in the code but couldn't really figure it out in there.

**Comment by pimruiter** [comment]
Hi Joost,

The tier pricing is really basic. You can create one price attribute for a customer group. After activating the tier pricing in the extra Akeneo Bundle options, you can map this attribute to the Magento customer group.

**Comment by rabillion** [comment]
Is an Akeneo Extension required for this? It is not possible to create tier prices in the standard version of Akeneo

**Comment by pimruiter** [comment]
> Is an Akeneo Extension required for this? It is not possible to create tier prices in the standard version of Akeneo

You can manage tierprices for customer groups in Akeneo with this Magento extension.

**Comment by rabillion** [comment]
> > Is an Akeneo Extension required for this? It is not possible to create tier prices in the standard version of Akeneo
> 
> You can manage tierprices for customer groups in Akeneo with this Magento extension.

Thanks for the quick reply.  So does this work with a standard price attribute from Akeneo?

**Comment by pimruiter** [comment]
> > > Is an Akeneo Extension required for this? It is not possible to create tier prices in the standard version of Akeneo
> > 
> > 
> > You can manage tierprices for customer groups in Akeneo with this Magento extension.
> 
> Thanks for the quick reply. So does this work with a standard price attribute from Akeneo?

The tier pricing is really basic. You can create one price attribute for a customer group. After activating the tier pricing in the extra Akeneo Bundle options, you can map this attribute to the Magento customer group.

**Comment by rabillion** [comment]
> > > > Is an Akeneo Extension required for this? It is not possible to create tier prices in the standard version of Akeneo
> > > 
> > > 
> > > You can manage tierprices for customer groups in Akeneo with this Magento extension.
> > 
> > 
> > Thanks for the quick reply. So does this work with a standard price attribute from Akeneo?
> 
> The tier pricing is really basic. You can create one price attribute for a customer group. After activating the tier pricing in the extra Akeneo Bundle options, you can map this attribute to the Magento customer group.

Thank you, we will try it out

**Comment by rabillion** [comment]
> v

We have now tested the function and unfortunately no tier prices are imported.
We have created a simple price attribute (scope is website) in Akeneo and assigned it to a customer group in Magento. Unfortunately, after importing the tier price remains empty. 
In your code plugin the condition does not apply [$exist](https://github.com/justbetter/magento2-akeneo-bundle/blob/174cad27142568585c65c3ca3c8ba10eba514ca7/Plugin/SetTierPrices.php#L101)
If I add the suffix manually (example $option['pim_type'] .'-WEBSITECODE-EUR'), the import hangs.
What are we missing? Can you please help?

**Comment by pimruiter** [comment]
> We have now tested the function and unfortunately no tier prices are imported. We have created a simple price attribute (scope is website) in Akeneo and assigned it to a customer group in Magento. Unfortunately, after importing the tier price remains empty. In your code plugin the condition does not apply [$exist](https://github.com/justbetter/magento2-akeneo-bundle/blob/174cad27142568585c65c3ca3c8ba10eba514ca7/Plugin/SetTierPrices.php#L101) If I add the suffix manually (example $option['pim_type'] .'-WEBSITECODE-EUR'), the import hangs. What are we missing? Can you please help?

Create a price attribute in Akeneo, the best practise is to use <code>-<customergroup>. Then within the mapping in the Akeneo connector use: <code>-<customergroup>-<currency> and map it to the right customer group. Let me know the result, I will update the docs of this extension according to your feedback.

**Comment by rabillion** [comment]
> > We have now tested the function and unfortunately no tier prices are imported. We have created a simple price attribute (scope is website) in Akeneo and assigned it to a customer group in Magento. Unfortunately, after importing the tier price remains empty. In your code plugin the condition does not apply [$exist](https://github.com/justbetter/magento2-akeneo-bundle/blob/174cad27142568585c65c3ca3c8ba10eba514ca7/Plugin/SetTierPrices.php#L101) If I add the suffix manually (example $option['pim_type'] .'-WEBSITECODE-EUR'), the import hangs. What are we missing? Can you please help?
> 
> Create a price attribute in Akeneo, the best practise is to use `<code>-<customergroup>`. Then within the mapping in the Akeneo connector use: `<code>-<customergroup>-<currency>` and map it to the right customer group. Let me know the result, I will update the docs of this extension according to your feedback.

Thank you again, we will try it out.
Another question came up. How does the assignment of the other prices and the graduation work(qty, percentage or fixed)?

**Comment by pimruiter** [comment]
> Thank you again, we will try it out. Another question came up. How does the assignment of the other prices and the graduation work(qty, percentage or fixed)?

It will not work. I do not recommend to store any prices in Akeneo in the first place. To make Akeneo the source for this kind of price logic is not the way to go.
